[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["pip install -r requirements_simple.txt"]

[phases.build]
cmds = []

[start]
cmd = "uvicorn main_simple:app --host 0.0.0.0 --port $PORT"
